export const allProblems = [
  { id: 1, name: "Two Sum", level: 1, completed: false },
  { id: 2, name: "Valid Parentheses", level: 1, completed: true },
  { id: 3, name: "Merge Two Sorted Lists", level: 1, completed: true },
  { id: 4, name: "Best Time to Buy Stock", level: 1, completed: false },
  { id: 5, name: "Valid Palindrome", level: 1, completed: false },
  { id: 6, name: "Binary Search", level: 1, completed: false },
  { id: 7, name: "Reverse Linked List", level: 1, completed: true },
  { id: 8, name: "Maximum Subarray", level: 1, completed: false },
  { id: 9, name: "Contains Duplicate", level: 1, completed: true },
  { id: 10, name: "Product of Array Except Self", level: 1, completed: false },
  { id: 11, name: "3Sum", level: 1, completed: false },
  { id: 12, name: "Container With Most Water", level: 1, completed: true },
  { id: 13, name: "Find Minimum in Rotated Sorted Array", level: 1, completed: false },
  { id: 14, name: "Longest Substring Without Repeating Characters", level: 1, completed: false },
  { id: 15, name: "Number of 1 Bits", level: 1, completed: true },
  { id: 16, name: "Climbing Stairs", level: 1, completed: true },
  { id: 17, name: "Coin Change", level: 1, completed: false },
  { id: 18, name: "House Robber", level: 1, completed: true },
  { id: 19, name: "Longest Palindromic Substring", level: 1, completed: false },
  { id: 20, name: "Valid Anagram", level: 1, completed: true },
  { id: 21, name: "Group Anagrams", level: 1, completed: false },
  { id: 22, name: "Top K Frequent Elements", level: 1, completed: false },
  { id: 23, name: "Encode and Decode Strings", level: 1, completed: true },
  { id: 24, name: "Halloumi Boxes", level: 2, completed: true },
  { id: 25, name: "Line Trip", level: 2, completed: true },
  { id: 26, name: "Cover in Water", level: 2, completed: true },
  { id: 27, name: "Game with Integers", level: 2, completed: true },
  { id: 28, name: "Jagged Swaps", level: 2, completed: true },
  { id: 29, name: "Sliding Window Maximum", level: 2, completed: false },
  { id: 30, name: "Longest Increasing Subsequence", level: 2, completed: false },
  { id: 31, name: "Word Break", level: 2, completed: true },
  { id: 32, name: "Combination Sum", level: 2, completed: false },
  { id: 33, name: "Word Search", level: 2, completed: false },
  { id: 34, name: "Rotate Image", level: 2, completed: true },
  { id: 35, name: "Spiral Matrix", level: 2, completed: false },
  { id: 36, name: "Jump Game", level: 2, completed: true },
  { id: 37, name: "Merge Intervals", level: 2, completed: false },
  { id: 38, name: "Insert Interval", level: 2, completed: false },
  { id: 39, name: "Non-overlapping Intervals", level: 2, completed: true },
  { id: 40, name: "Meeting Rooms", level: 2, completed: true },
  { id: 41, name: "Validate Binary Search Tree", level: 2, completed: false },
  { id: 42, name: "Kth Smallest Element in BST", level: 2, completed: false },
  { id: 43, name: "Lowest Common Ancestor of BST", level: 2, completed: true },
  { id: 44, name: "Implement Trie", level: 2, completed: false },
  { id: 45, name: "Design Add and Search Words Data Structure", level: 2, completed: false },
  { id: 46, name: "Word Search II", level: 2, completed: false },
  { id: 47, name: "Course Schedule", level: 2, completed: true },
  { id: 48, name: "Course Schedule II", level: 2, completed: false },
  { id: 49, name: "Number of Islands", level: 2, completed: true },
  { id: 50, name: "Clone Graph", level: 2, completed: false },
  { id: 51, name: "Pacific Atlantic Water Flow", level: 2, completed: false },
  { id: 52, name: "Surrounded Regions", level: 2, completed: true },
  { id: 53, name: "Rotting Oranges", level: 2, completed: false },
  { id: 54, name: "Walls and Gates", level: 2, completed: false },
  { id: 55, name: "Longest Consecutive Sequence", level: 2, completed: true },
  { id: 56, name: "Alien Dictionary", level: 2, completed: false },
  { id: 57, name: "Graph Valid Tree", level: 2, completed: false },
  { id: 58, name: "Number of Connected Components", level: 2, completed: true },
  { id: 59, name: "Subtree of Another Tree", level: 2, completed: false },
  { id: 60, name: "Construct Binary Tree from Preorder and Inorder", level: 2, completed: false },
  { id: 61, name: "Maximum Depth of Binary Tree", level: 2, completed: true },
  { id: 62, name: "Same Tree", level: 2, completed: true },
  { id: 63, name: "Invert Binary Tree", level: 2, completed: true },
  { id: 64, name: "Binary Tree Maximum Path Sum", level: 2, completed: false },
  { id: 65, name: "Binary Tree Level Order Traversal", level: 2, completed: false },
  { id: 66, name: "Serialize and Deserialize Binary Tree", level: 2, completed: false },
]


// const questions = [
//   {
//     id: 1,
//     href: 'https://codeforces.com/problemset/problem/1/A',
//     name: 'Theatre Square',
//     level: 1,
//     completed: false
//   },
//   {
//     id: 2,
//     href: 'https://codeforces.com/problemset/problem/2/B',
//     name: 'The least round way',
//     level: 1,
//     completed: false
//   },
//   {
//     id: 3,
//     href: 'https://codeforces.com/problemset/problem/3/C',
//     name: 'Tic-tac-toe',
//     level: 1,
//     completed: false
//   },
//   {
//     id: 4,
//     href: 'https://codeforces.com/problemset/problem/4/D',
//     name: 'Mysterious Present',
//     level: 1,
//     completed: false
//   },
//   {
//     id: 5,
//     href: 'https://codeforces.com/problemset/problem/5/E',
//     name: 'Bindian Signalizing',
//     level: 1,
//     completed: false
//   }
// ]

// async function enrichQuestions() {
//   const apiUrl = 'https://codeforces.com/api/problemset.problems';

//   try {
//     const response = await fetch(apiUrl);
//     const data = await response.json();

//     if (data.status !== 'OK') throw new Error("API error");

//     const problems = data.result.problems;

//     questions.forEach(q => {
//       // Extract contestId and index from href
//       const parts = q.href.split('/').slice(-2); // ["1", "A"]
//       const contestId = parseInt(parts[0]);
//       const index = parts[1];

//       // Find the problem in the API data
//       const match = problems.find(
//         p => p.contestId === contestId && p.index === index
//       );

//       if (match) {
//         q.name = match.name;
//         const rating = match.rating || 0;
//         q.level = rating <= 900 ? 0 : 1;
//       } else {
//         q.name = "Not Found";
//         q.level = -1;
//       }
//     });

//     console.log(questions);
//     // console.log(questions);
    
//   } catch (error) {
//     console.error("Failed to fetch Codeforces problems:", error);
//   }
// }

// enrichQuestions();

// const questions= [
//   { "id": 1, "href": "https://codeforces.com/group/MWSDmqGsZm/contest/219158/problem/X", "name": "", "level": -1, "completed": false },
//   { "id": 2, "href": "https://codeforces.com/group/MWSDmqGsZm/contest/219432/problem/X", "name": "", "level": -1, "completed": false },
//   { "id": 3, "href": "https://codeforces.com/group/MWSDmqGsZm/contest/219432/problem/W", "name": "", "level": -1, "completed": false },
//   { "id": 4, "href": "https://codeforces.com/group/MWSDmqGsZm/contest/219774/problem/H", "name": "", "level": -1, "completed": false },
//   { "id": 5, "href": "https://codeforces.com/group/MWSDmqGsZm/contest/219774/problem/U", "name": "", "level": -1, "completed": false },
//   { "id": 6, "href": "https://codeforces.com/group/MWSDmqGsZm/contest/219774/problem/Q", "name": "", "level": -1, "completed": false },
//   { "id": 7, "href": "https://codeforces.com/contest/1927/problem/A", "name": "", "level": -1, "completed": false },
//   { "id": 8, "href": "https://codeforces.com/contest/1926/problem/B", "name": "", "level": -1, "completed": false },
//   { "id": 9, "href": "https://codeforces.com/group/MWSDmqGsZm/contest/219856/problem/K", "name": "", "level": -1, "completed": false },
//   { "id": 10, "href": "https://codeforces.com/group/MWSDmqGsZm/contest/223338/problem/A", "name": "", "level": -1, "completed": false },
//   { "id": 11, "href": "https://codeforces.com/group/MWSDmqGsZm/contest/219774/problem/M", "name": "", "level": -1, "completed": false },
//   { "id": 12, "href": "https://codeforces.com/group/MWSDmqGsZm/contest/219856/problem/F", "name": "", "level": -1, "completed": false },
//   { "id": 13, "href": "https://codeforces.com/contest/1929/problem/B", "name": "", "level": -1, "completed": false },
//   { "id": 14, "href": "https://codeforces.com/group/c3FDl9EUi9/contest/262795/problem/A", "name": "", "level": -1, "completed": false },
//   { "id": 15, "href": "https://codeforces.com/problemset/problem/1920/A", "name": "", "level": -1, "completed": false },
//   { "id": 16, "href": "https://codeforces.com/group/c3FDl9EUi9/contest/262795/problem/K", "name": "", "level": -1, "completed": false },
//   { "id": 17, "href": "https://codeforces.com/contest/313/problem/B", "name": "", "level": -1, "completed": false },
//   { "id": 18, "href": "https://codeforces.com/contest/1950/problem/A", "name": "", "level": -1, "completed": false },
//   { "id": 19, "href": "https://codeforces.com/problemset/problem/1916/B", "name": "", "level": -1, "completed": false },
//   { "id": 20, "href": "https://codeforces.com/contest/1850/problem/A", "name": "", "level": -1, "completed": false },
//   { "id": 21, "href": "https://codeforces.com/contest/1918/problem/A", "name": "", "level": -1, "completed": false },
//   { "id": 22, "href": "https://codeforces.com/contest/1692/problem/A", "name": "", "level": -1, "completed": false },
//   { "id": 23, "href": "https://codeforces.com/contest/707/problem/A", "name": "", "level": -1, "completed": false },
//   { "id": 24, "href": "https://codeforces.com/contest/1829/problem/A", "name": "", "level": -1, "completed": false },
//   { "id": 25, "href": "https://codeforces.com/problemset/problem/1555/A", "name": "", "level": -1, "completed": false },
//   { "id": 26, "href": "https://codeforces.com/contest/1669/problem/A", "name": "", "level": -1, "completed": false },
//   { "id": 27, "href": "https://codeforces.com/contest/1593/problem/A", "name": "", "level": -1, "completed": false },
//   { "id": 28, "href": "https://codeforces.com/problemset/problem/1490/C", "name": "", "level": -1, "completed": false },
//   { "id": 29, "href": "https://codeforces.com/contest/1850/problem/B", "name": "", "level": -1, "completed": false },
//   { "id": 30, "href": "https://codeforces.com/problemset/problem/1475/A", "name": "", "level": -1, "completed": false },
//   { "id": 31, "href": "https://codeforces.com/contest/1760/problem/A", "name": "", "level": -1, "completed": false },
//   { "id": 32, "href": "https://codeforces.com/contest/1859/problem/A", "name": "", "level": -1, "completed": false },
//   { "id": 33, "href": "https://codeforces.com/contest/1742/problem/B", "name": "", "level": -1, "completed": false },
//   { "id": 34, "href": "https://codeforces.com/contest/1619/problem/B", "name": "", "level": -1, "completed": false },
//   { "id": 35, "href": "https://codeforces.com/contest/1722/problem/A", "name": "", "level": -1, "completed": false },
//   { "id": 36, "href": "https://codeforces.com/problemset/problem/1607/B", "name": "", "level": -1, "completed": false },
//   { "id": 37, "href": "https://codeforces.com/problemset/problem/443/A", "name": "", "level": -1, "completed": false },
//   { "id": 38, "href": "https://codeforces.com/contest/1873/problem/C", "name": "", "level": -1, "completed": false },
//   { "id": 39, "href": "https://codeforces.com/problemset/problem/510/A", "name": "", "level": -1, "completed": false },
//   { "id": 40, "href": "https://codeforces.com/problemset/problem/1878/C", "name": "", "level": -1, "completed": false },
//   { "id": 41, "href": "https://codeforces.com/problemset/problem/1512/A", "name": "", "level": -1, "completed": false },
//   { "id": 42, "href": "https://codeforces.com/problemset/problem/1742/C", "name": "", "level": -1, "completed": false },
//   { "id": 43, "href": "https://codeforces.com/contest/1950/problem/C", "name": "", "level": -1, "completed": false },
//   { "id": 44, "href": "https://codeforces.com/problemset/problem/1294/C", "name": "", "level": -1, "completed": false },
//   { "id": 45, "href": "https://codeforces.com/contest/34/problem/A", "name": "", "level": -1, "completed": false },
//   { "id": 46, "href": "https://codeforces.com/contest/1715/problem/A", "name": "", "level": -1, "completed": false },
//   { "id": 47, "href": "https://codeforces.com/contest/1957/problem/A", "name": "", "level": -1, "completed": false },
//   { "id": 48, "href": "https://codeforces.com/contest/1722/problem/C", "name": "", "level": -1, "completed": false },
//   { "id": 49, "href": "https://codeforces.com/contest/1957/problem/A", "name": "", "level": -1, "completed": false },
//   { "id": 50, "href": "https://codeforces.com/problemset/problem/1445/B", "name": "", "level": -1, "completed": false },
//   { "id": 51, "href": "https://codeforces.com/contest/1858/problem/A", "name": "", "level": -1, "completed": false },
//   { "id": 52, "href": "https://codeforces.com/contest/1713/problem/A", "name": "", "level": -1, "completed": false },
//   { "id": 53, "href": "https://codeforces.com/problemset/problem/702/A", "name": "", "level": -1, "completed": false },
//   { "id": 54, "href": "https://codeforces.com/contest/580/problem/A", "name": "", "level": -1, "completed": false },
//   { "id": 55, "href": "https://codeforces.com/problemset/problem/381/A", "name": "", "level": -1, "completed": false },
//   { "id": 56, "href": "https://codeforces.com/problemset/problem/118/A", "name": "", "level": -1, "completed": false },
//   { "id": 57, "href": "https://codeforces.com/problemset/problem/996/A", "name": "", "level": -1, "completed": false },
//   { "id": 58, "href": "https://codeforces.com/contest/1850/problem/E", "name": "", "level": -1, "completed": false },
//   { "id": 59, "href": "https://codeforces.com/contest/910/problem/A", "name": "", "level": -1, "completed": false },
//   { "id": 60, "href": "https://codeforces.com/problemset/problem/1604/B", "name": "", "level": -1, "completed": false },
//   { "id": 61, "href": "https://codeforces.com/problemset/problem/1954/A", "name": "", "level": -1, "completed": false },
//   { "id": 62, "href": "https://codeforces.com/contest/1829/problem/F", "name": "", "level": -1, "completed": false },
//   { "id": 63, "href": "https://codeforces.com/contest/1972/problem/B", "name": "", "level": -1, "completed": false },
//   { "id": 64, "href": "https://codeforces.com/group/MWSDmqGsZm/contest/219158/problem/Z", "name": "", "level": -1, "completed": false },
//   { "id": 65, "href": "https://codeforces.com/problemset/problem/1951/A", "name": "", "level": -1, "completed": false },
//   { "id": 66, "href": "https://codeforces.com/problemset/problem/1476/A", "name": "", "level": -1, "completed": false },
//   { "id": 67, "href": "https://codeforces.com/contest/1973/problem/A", "name": "", "level": -1, "completed": false },
//   { "id": 68, "href": "https://codeforces.com/contest/1791/problem/C", "name": "", "level": -1, "completed": false },
//   { "id": 69, "href": "https://codeforces.com/problemset/problem/1916/B", "name": "", "level": -1, "completed": false },
//   { "id": 70, "href": "https://codeforces.com/contest/1972/problem/B", "name": "", "level": -1, "completed": false },
//   { "id": 71, "href": "https://codeforces.com/contest/1736/problem/A", "name": "", "level": -1, "completed": false },
//   { "id": 72, "href": "https://codeforces.com/problemset/problem/1873/D", "name": "", "level": -1, "completed": false },
//   { "id": 73, "href": "https://codeforces.com/problemset/problem/1974/A", "name": "", "level": -1, "completed": false },
//   { "id": 74, "href": "https://codeforces.com/problemset/problem/1843/A", "name": "", "level": -1, "completed": false },
//   { "id": 75, "href": "https://codeforces.com/problemset/problem/1974/B", "name": "", "level": -1, "completed": false },
//   { "id": 76, "href": "https://codeforces.com/problemset/problem/1971/A", "name": "", "level": -1, "completed": false },
//   { "id": 77, "href": "https://codeforces.com/problemset/problem/1980/B", "name": "", "level": -1, "completed": false },
//   { "id": 78, "href": "https://codeforces.com/contest/1968/problem/A", "name": "", "level": -1, "completed": false },
//   { "id": 79, "href": "https://codeforces.com/contest/1971/problem/D", "name": "", "level": -1, "completed": false },
//   { "id": 80, "href": "https://codeforces.com/problemset/problem/510/A", "name": "", "level": -1, "completed": false },
//   { "id": 81, "href": "https://codeforces.com/contest/1676/problem/A", "name": "", "level": -1, "completed": false },
//   { "id": 82, "href": "https://codeforces.com/contest/1977/problem/A", "name": "", "level": -1, "completed": false },
//   { "id": 83, "href": "https://codeforces.com/problemset/problem/1972/B", "name": "", "level": -1, "completed": false },
//   { "id": 84, "href": "https://codeforces.com/problemset/problem/275/A", "name": "", "level": -1, "completed": false },
//   { "id": 85, "href": "https://codeforces.com/contest/1984/problem/A", "name": "", "level": -1, "completed": false },
//   { "id": 86, "href": "https://codeforces.com/contest/1980/problem/B", "name": "", "level": -1, "completed": false },
//   { "id": 87, "href": "https://codeforces.com/problemset/problem/1890/A", "name": "", "level": -1, "completed": false },
//   { "id": 88, "href": "https://codeforces.com/problemset/problem/749/A", "name": "", "level": -1, "completed": false },
//   { "id": 89, "href": "https://codeforces.com/problemset/problem/1984/A", "name": "", "level": -1, "completed": false },
//   { "id": 90, "href": "https://codeforces.com/problemset/problem/1985/B", "name": "", "level": -1, "completed": false },
//   { "id": 91, "href": "https://codeforces.com/problemset/problem/1981/A", "name": "", "level": -1, "completed": false },
//   { "id": 92, "href": "https://codeforces.com/problemset/problem/1987/A", "name": "", "level": -1, "completed": false },
//   { "id": 93, "href": "https://codeforces.com/problemset/problem/1291/A", "name": "", "level": -1, "completed": false },
//   { "id": 94, "href": "https://codeforces.com/problemset/problem/1931/B", "name": "", "level": -1, "completed": false },
//   { "id": 95, "href": "https://codeforces.com/problemset/problem/1985/D", "name": "", "level": -1, "completed": false },
//   { "id": 96, "href": "https://codeforces.com/problemset/problem/1915/D", "name": "", "level": -1, "completed": false },
//   { "id": 97, "href": "https://codeforces.com/contest/1990/problem/A", "name": "", "level": -1, "completed": false },
//   { "id": 98, "href": "https://codeforces.com/contest/1988/problem/A", "name": "", "level": -1, "completed": false },
//   { "id": 99, "href": "https://codeforces.com/contest/1986/problem/A", "name": "", "level": -1, "completed": false },
//   { "id": 100, "href": "https://codeforces.com/contest/1883/problem/C", "name": "", "level": -1, "completed": false },
//   { "id": 101, "href": "https://codeforces.com/problemset/problem/1794/A", "name": "", "level": -1, "completed": false },
//   { "id": 102, "href": "https://codeforces.com/contest/1236/problem/A", "name": "", "level": -1, "completed": false },
//   { "id": 103, "href": "https://codeforces.com/contest/1716/problem/A", "name": "", "level": -1, "completed": false },
//   { "id": 104, "href": "https://codeforces.com/contest/1059/problem/A", "name": "", "level": -1, "completed": false },
//   { "id": 105, "href": "https://codeforces.com/contest/1991/problem/A", "name": "", "level": -1, "completed": false },
//   { "id": 106, "href": "https://codeforces.com/contest/1418/problem/A", "name": "", "level": -1, "completed": false },
//   { "id": 107, "href": "https://codeforces.com/contest/1879/problem/A", "name": "", "level": -1, "completed": false },
//   { "id": 108, "href": "https://codeforces.com/contest/1747/problem/B", "name": "", "level": -1, "completed": false },
//   { "id": 109, "href": "https://codeforces.com/contest/1574/problem/A", "name": "", "level": -1, "completed": false },
//   { "id": 110, "href": "https://codeforces.com/problemset/problem/1421/A", "name": "", "level": -1, "completed": false },
//   { "id": 111, "href": "https://codeforces.com/problemset/problem/579/A", "name": "", "level": -1, "completed": false },
//   { "id": 112, "href": "https://codeforces.com/contest/1999/problem/C", "name": "", "level": -1, "completed": false },
//   { "id": 113, "href": "https://codeforces.com/contest/1900/problem/A", "name": "", "level": -1, "completed": false },
//   { "id": 114, "href": "https://codeforces.com/group/MWSDmqGsZm/contest/223339/problem/X", "name": "", "level": -1, "completed": false },
//   { "id": 115, "href": "https://codeforces.com/contest/1758/problem/B", "name": "", "level": -1, "completed": false },
//   { "id": 116, "href": "https://codeforces.com/problemset/problem/1634/A", "name": "", "level": -1, "completed": false },
//   { "id": 117, "href": "https://codeforces.com/contest/1990/problem/A", "name": "", "level": -1, "completed": false },
//   { "id": 118, "href": "https://codeforces.com/contest/1995/problem/A", "name": "", "level": -1, "completed": false },
//   { "id": 119, "href": "https://codeforces.com/contest/1990/problem/A", "name": "", "level": -1, "completed": false },
//   { "id": 120, "href": "https://codeforces.com/contest/1539/problem/A", "name": "", "level": -1, "completed": false },
//   { "id": 121, "href": "https://codeforces.com/problemset/problem/2004/A", "name": "", "level": -1, "completed": false },
//   { "id": 122, "href": "https://codeforces.com/contest/746/problem/B", "name": "", "level": -1, "completed": false },
//   { "id": 123, "href": "https://codeforces.com/contest/1559/problem/A", "name": "", "level": -1, "completed": false },
//   { "id": 124, "href": "https://codeforces.com/contest/1238/problem/A", "name": "", "level": -1, "completed": false },
//   { "id": 125, "href": "https://codeforces.com/contest/1537/problem/B", "name": "", "level": -1, "completed": false },
//   { "id": 126, "href": "https://codeforces.com/contest/1005/problem/B", "name": "", "level": -1, "completed": false },
//   { "id": 127, "href": "https://codeforces.com/problemset/problem/1849/B", "name": "", "level": -1, "completed": false },
//   { "id": 128, "href": "https://codeforces.com/problemset/problem/1918/B", "name": "", "level": -1, "completed": false },
//   { "id": 129, "href": "https://codeforces.com/problemset/problem/1705/B", "name": "", "level": -1, "completed": false },
//   { "id": 130, "href": "https://codeforces.com/problemset/problem/1617/B", "name": "", "level": -1, "completed": false },
//   { "id": 131, "href": "https://codeforces.com/problemset/problem/1537/B", "name": "", "level": -1, "completed": false },
//   { "id": 132, "href": "https://codeforces.com/problemset/problem/1462/C", "name": "", "level": -1, "completed": false },
//   { "id": 133, "href": "https://codeforces.com/problemset/problem/768/A", "name": "", "level": -1, "completed": false },
//   { "id": 134, "href": "https://codeforces.com/problemset/problem/1823/B", "name": "", "level": -1, "completed": false },
//   { "id": 135, "href": "https://codeforces.com/problemset/problem/1569/B", "name": "", "level": -1, "completed": false },
//   { "id": 136, "href": "https://codeforces.com/contest/2008/problem/A", "name": "", "level": -1, "completed": false },
//   { "id": 137, "href": "https://codeforces.com/contest/2008/problem/B", "name": "", "level": -1, "completed": false },
//   { "id": 138, "href": "https://codeforces.com/contest/2009/problem/C", "name": "", "level": -1, "completed": false },
//   { "id": 139, "href": "https://codeforces.com/contest/2007/problem/A", "name": "", "level": -1, "completed": false },
//   { "id": 140, "href": "https://codeforces.com/contest/2007/problem/B", "name": "", "level": -1, "completed": false },
//   { "id": 141, "href": "https://codeforces.com/contest/2010/problem/B", "name": "", "level": -1, "completed": false },
//   { "id": 142, "href": "https://codeforces.com/problemset/problem/1837/C", "name": "", "level": -1, "completed": false },
//   { "id": 143, "href": "https://codeforces.com/problemset/problem/1665/B", "name": "", "level": -1, "completed": false },
//   { "id": 144, "href": "https://codeforces.com/problemset/problem/1800/B", "name": "", "level": -1, "completed": false },
//   { "id": 145, "href": "https://codeforces.com/problemset/problem/1632/B", "name": "", "level": -1, "completed": false },
//   { "id": 146, "href": "https://codeforces.com/problemset/problem/1834/B", "name": "", "level": -1, "completed": false },
//   { "id": 147, "href": "https://codeforces.com/problemset/problem/1829/D", "name": "", "level": -1, "completed": false },
//   { "id": 148, "href": "https://codeforces.com/problemset/problem/1992/C", "name": "", "level": -1, "completed": false },
//   { "id": 149, "href": "https://codeforces.com/contest/2005/problem/A", "name": "", "level": -1, "completed": false },
//   { "id": 150, "href": "https://codeforces.com/contest/2005/problem/B1", "name": "", "level": -1, "completed": false },
//   { "id": 151, "href": "https://codeforces.com/contest/2005/problem/B2", "name": "", "level": -1, "completed": false },
//   { "id": 152, "href": "https://codeforces.com/contest/1902/problem/A", "name": "", "level": -1, "completed": false },
//   { "id": 153, "href": "https://codeforces.com/contest/1902/problem/B", "name": "", "level": -1, "completed": false },
//   { "id": 154, "href": "https://codeforces.com/contest/1904/problem/B", "name": "", "level": -1, "completed": false },
//   { "id": 155, "href": "https://codeforces.com/contest/2013/problem/A", "name": "", "level": -1, "completed": false },
//   { "id": 156, "href": "https://codeforces.com/contest/2013/problem/B", "name": "", "level": -1, "completed": false },
//   { "id": 157, "href": "https://codeforces.com/contest/2014/problem/B", "name": "", "level": -1, "completed": false },
//   { "id": 158, "href": "https://codeforces.com/contest/2014/problem/A", "name": "", "level": -1, "completed": false },
//   { "id": 159, "href": "https://codeforces.com/problemset/problem/1077/B", "name": "", "level": -1, "completed": false },
//   { "id": 160, "href": "https://codeforces.com/contest/2013/problem/C", "name": "", "level": -1, "completed": false },
//   { "id": 161, "href": "https://codeforces.com/contest/1851/problem/B", "name": "", "level": -1, "completed": false },
//   { "id": 162, "href": "https://codeforces.com/contest/2019/problem/A", "name": "", "level": -1, "completed": false },
//   { "id": 163, "href": "https://codeforces.com/contest/1669/problem/B", "name": "", "level": -1, "completed": false },
//   { "id": 164, "href": "https://codeforces.com/contest/1998/problem/A", "name": "", "level": -1, "completed": false },
//   { "id": 165, "href": "https://codeforces.com/contest/2020/problem/A", "name": "", "level": -1, "completed": false },
//   { "id": 166, "href": "https://codeforces.com/problemset/problem/1475/B", "name": "", "level": -1, "completed": false },
//   { "id": 167, "href": "https://codeforces.com/problemset/problem/1593/B", "name": "", "level": -1, "completed": false },
//   { "id": 168, "href": "https://codeforces.com/contest/1033/problem/B", "name": "", "level": -1, "completed": false },
//   { "id": 169, "href": "https://codeforces.com/problemset/problem/318/A", "name": "", "level": -1, "completed": false },
//   { "id": 170, "href": "https://codeforces.com/contest/96/problem/B", "name": "", "level": -1, "completed": false }
// ]